[server]
headless = true
port = 8501
enableCORS = false

[theme]
# Light / Dark mode는 app.py에서 시간 기반으로 설정하고 있으므로 여기선 기본 설정만 적용
primaryColor = "#0077C8"         # 버튼, 링크 등 주요 색상
backgroundColor = "#FFFFFF"      # 기본 배경색 (Light Mode 기준)
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"              # 기본 폰트: serif, sans serif, monospace

[client]
toolbarMode = "minimal"          # 오른쪽 위 Toolbar 최소화
