# ✅ 오픈 API (DataLab)
NAVER_API_KEY = "네이버 DataLab API 클라이언트 ID"
NAVER_SECRET_KEY = "네이버 DataLab API 시크릿 키"

# ✅ 검색광고 API (SearchAD)
NAVER_AD_API_KEY = "엑세스 라이선스 키"
NAVER_AD_SECRET_KEY = "비밀 키"
NAVER_CUSTOMER_ID = "고객 ID (숫자)"
